ForgeRock/forgerock-web-login-framework

.whitesource
whitesource config file addition
=> ci(whitesource): add whitesource config

.github/workflows/preview-closed.yml, .whitesource
two fixes: One - we need preview -close to have the docker image i made so that is why it fails.
two: we need to add the base branch for whitesource per bruno
=> ci: update-preview-and-whitesource

.github/workflows/ci.yml, .github/workflows/dependabot-auto-label.yml, .github/workflows/release.yml
Basically the large swath of problems was because i was unaware that secrets have a special dependabot section so that you can share secrets with dependabot. so i've added those secrets there and made the small fix here.
=> ci:fix-label

.github/workflows/preview.yml, .github/workflows/release.yml, .lighthouserc.cjs
this adds private key as a secret from my account to help sign the commits
=> chore(update-signing): sign-commits-ci

.github/dependabot.yml, .github/workflows/release.yml, Dockerfile, docker-compose.yml
lock crazy max dependency and ignore it in dependabot config
removed dev to save space on okteto since we do not use it.
also updated docker file to be a little better
=> ci(dependabot): lock crazy max and ignore with dependabot

.github/workflows/preview.yml
remove lighthouse from ci because it causes a bit more problems than i wanted.
=> remove lighthouse

package-lock.json
package-lock was bad on install for previous release
=> fix(widget): update-package-lock

.github/workflows/ci.yml, .husky/pre-commit, .husky/pre-push, package-lock.json, package.json
ci refactor includes adding chromatic back to the pipeline, and running accessibility tests seperately. i refactored to cache npm install and split it into two jobs so that we are not redoing the same steps overr and over
https://bugster.forgerock.org/jira/browse/SDKS-2256
=> ci(ci.yml): refactor ci for release

README.md
adding amesssage in docs and forcing a release cause the last commit was refactor but should have triggered a release.
=> update-docs 

package/package.json
need to provide css in export map
=> fix(add-back-css): css was removed ona ccident

.eslintrc.cjs, .gitignore, .storybook/main.js, package-lock.json, package.json
fix turbo snap to run less snapshots and builds with chromatic
=> ci(storybook): fix turbo snap

.svelte-kit/tsconfig.json, package/CHANGELOG.md, package/index.js, package/package.json, package/widget.css, src/lib/journey/_utilities/map-stage.utilities.test.ts, src/lib/journey/_utilities/map-stage.utilities.ts, src/lib/journey/_utilities/step.mock.ts, src/lib/journey/callbacks/_utilities/callback.utilities.ts, src/lib/journey/callbacks/_utilities/policies.story.svelte, src/lib/journey/callbacks/_utilities/policies.svelte, src/lib/journey/callbacks/password/validated-create-password.svelte, src/lib/journey/config.store.ts, src/lib/journey/journey.interfaces.ts, src/lib/journey/journey.store.ts, src/lib/journey/stages/_utilities/stage.utilities.ts, src/lib/journey/stages/index.ts, src/lib/journey/stages/login.svelte, src/lib/journey/stages/registration.svelte, src/lib/journey/stages/stages.story.svelte, src/lib/journey/stages/step.mock.ts, src/lib/widget/_utilities/api.utilities.ts, src/routes/e2e/widget/modal/+page.svelte
This PR focuses on bug fixes and improvements throughout the journey portion of functionality.
1. Allows for journey config to be partially configured by dev, rather than all or nothing
2. It removes the auto restart after logout as it was unnecessary and resulting in irrelevant journeys rendering
3. Fixes journey restart after failure by using the journey stack; original attempt at fixing didn't take into account journey switching
4. Renames stages for login and registration to be "DefaultLogin" and "DefaultRegistration", rather than "UsernamePassword" and "Registration", respectively
5. Changes the display of policy rules for callback components as default to opt-in
=> fix(journeys): fix stages, journey restarts & config, policy display, remove restart after logout

src/lib/widget/_utilities/api.utilities.ts, tests/widget/inline/widget-inline.register.test.js
the request export was losing the `this` value. It needed to be bound to the HttpClient from the SDK.
=> fix(index.svelte): bind http client to request

package-lock.json, package/CHANGELOG.md, package/index.js, src/lib/journey/journey.svelte
This just prevents the crashing of the widget and reports a readable message when the widget is instantiated without configuration being set
=> fix(configuration): improve handling and reporting of missing configuration

src/lib/components/primitives/select/select.svelte, src/lib/journey/callbacks/password/base.svelte, src/lib/journey/callbacks/password/confirm-input.svelte
the password confirmation field should not be of focus, and the required fields should be required when a password is inputted
=> fix(base.svelte): fix focus on password field

.scripts/processTypes.mjs, package/package.json
release in ci was broken because we missed two places to update the types file
=> fix(types.ts): rename the types file where we missed it and fix release

README.md, package/README.md
Patch release because we didn't fix the readme file 🐶
=> fix(readme): fix-readme-patch

package/package.json
remove files because its not needed and using it makes it so only whats in that array is included
=> fix(files): files in package.json means it only updates whats in there

README.md
Updated README using content from the product docs on https://backstage.forgerock.com/docs
=> docs: Update README to match product documentation. (SDKS-2432)

.github/workflows/ci.yml, .github/workflows/release.yml, .releaserc.json, package-lock.json, package.json
node16 is EOL and we should be testing on 18 and 20
=> ci(githubactions): update-node-in-ci

package-lock.json, package.json, src/lib/journey/_utilities/callback-mapper.svelte, src/lib/journey/callbacks/recaptcha/helper-types.d.ts, src/lib/journey/callbacks/recaptcha/recaptcha.svelte
support recaptcha v2 in login widget. This does not include v3 support. hcaptcha is supported. invisible recaptcha is not.
https://bugster.forgerock.org/jira/browse/SDKS-2003
=> feat(recaptcha): support-recaptcha-v2

package/index.js, src/lib/journey/journey.interfaces.ts, src/lib/journey/journey.store.ts
creates new extended interface from StepOptions to support LW needed types. Adjust prevStep to be optional
=> fix(fixing-types): journey-type-updates

package/CHANGELOG.md, package/package.json
fix release in changelog to illustrate version 1.2.1 beacuse we had to patch
=> style(release-notes): fixing changelog per fixing of release

.env.example, package-lock.json, package.json, tests/utilities/manage-demo-users.js, tests/widget/inline/widget-device-profile.test.js, tests/widget/inline/widget-inline.es.test.js, tests/widget/inline/widget-inline.login-2step.a11y.test.js, tests/widget/inline/widget-inline.register.test.js, tests/widget/inline/widget-inline.stage-attribute.test.js, tests/widget/inline/widget-inline.test.js, tests/widget/modal/widget-modal.email-suspend.test.js, tests/widget/modal/widget-modal.login-2step.a11y.test.js, tests/widget/modal/widget-modal.login-social-redirect.test.js, tests/widget/modal/widget-modal.login-with-misc-callbacks.test.js, tests/widget/modal/widget-modal.login.a11y.test.js, tests/widget/modal/widget-modal.login.test.js, tests/widget/modal/widget-modal.qr-code.test.js, tests/widget/modal/widget-modal.register.test.js, tests/widget/modal/widget-modal.us_es.test.js
It crates and deletes demo users for e2e tests.
FYI: Tests failing because tenant needs more configuration
=> ci: manage-demo-users

tests/README.md
Adds a new readme file describing how to use and set up Frodo CLI
=> docs: new readme file
